# Generated by Django 3.2.4 on 2021-06-14 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HWapp', '0002_auto_20210614_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='HWapp.category'),
        ),
    ]
