# Generated by Django 3.2.4 on 2021-06-16 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HWapp', '0006_alter_product_men_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menproduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='men/%y')),
                ('name', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('description', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Product_men',
        ),
    ]
