# Generated by Django 3.2.4 on 2021-06-17 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HWapp', '0009_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='email',
            new_name='email_address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='fristname',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='password',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phone',
        ),
        migrations.AddField(
            model_name='customer',
            name='first_name',
            field=models.CharField(default='NULL', max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_name',
            field=models.CharField(default='NULL', max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='login_password',
            field=models.CharField(default='NULL', max_length=500),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone_num',
            field=models.CharField(default='NULL', max_length=15),
        ),
    ]
