# Generated by Django 3.2.4 on 2021-06-24 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HWapp', '0013_auto_20210622_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
