# Generated by Django 3.2.4 on 2021-06-28 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HWapp', '0017_auto_20210628_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Order_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HWapp.request'),
        ),
    ]
